import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { DatabaseSync } from 'node:sqlite';
import { createStorage } from '../server/storage.js';
import { createDb } from '../server/db.js';
import { migrateLegacyStorage } from '../server/migration.js';

test('legacy aggregate archive is split and empty turn zip is removed', async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'chat-v6-migrate-'));
  const storage = createStorage(root); await storage.init();
  const old = new DatabaseSync(storage.dbPath);
  old.exec(`CREATE TABLE conversations(id TEXT PRIMARY KEY, owner_id TEXT, title TEXT, share_enabled INTEGER, share_token TEXT, created_at INTEGER, updated_at INTEGER);
    CREATE TABLE turns(conversation_id TEXT, turn_no INTEGER, model_id TEXT, status TEXT, has_attachments INTEGER, attachment_ready INTEGER, attachment_size INTEGER, question TEXT, answer TEXT, created_at INTEGER, updated_at INTEGER);
    INSERT INTO conversations VALUES('c1','u1','old',1,'share-old',1,1);
    INSERT INTO turns VALUES('c1',1,'m1','completed',1,1,0,'q1','a1',1,1);
    INSERT INTO turns VALUES('c1',2,'m1','completed',1,1,0,'q2','a2',1,1);
    INSERT INTO turns VALUES('c1',3,'m1','completed',1,1,0,'q3','a3',1,1);`);
  old.close();
  fs.writeFileSync(storage.textPath('c1'), '{"type":"question","turnNo":1,"content":"q1"}\n{"type":"answer","turnNo":1,"content":"a1"}\n');
  const stage = path.join(root, 'stage'); fs.mkdirSync(stage);
  fs.writeFileSync(path.join(stage, 'one.txt'), 'one');
  assert.equal(spawnSync('zip',['-q','1.zip','one.txt'],{cwd:stage}).status,0);
  fs.writeFileSync(path.join(stage,'2.zip'), Buffer.concat([Buffer.from('504b0506','hex'), Buffer.alloc(18)]));
  fs.writeFileSync(path.join(stage, 'three.txt'), 'three');
  assert.equal(spawnSync('zip',['-q','3.zip','three.txt'],{cwd:stage}).status,0);
  assert.equal(spawnSync('zip',['-q',path.join(storage.chatDir,'c1.attachments.bin'),'1.zip','2.zip','3.zip'],{cwd:stage}).status,0);
  const db = createDb(storage.dbPath,{defaultOwnerId:'u1',defaultModelId:'m1',validModelIds:new Set(['m1'])});
  await migrateLegacyStorage({db,storage,config:{auth:{users:[{id:'u1'}]},models:[{id:'m1'}]}});
  assert.equal(fs.existsSync(storage.attachmentPath('c1',1)),true);
  assert.equal(fs.existsSync(storage.attachmentPath('c1',2)),false);
  assert.equal(fs.existsSync(storage.attachmentPath('c1',3)),true);
  assert.equal(fs.existsSync(path.join(storage.chatDir,'c1.attachments.bin')),false);
  assert.equal(db.getTurn('c1',2).has_attachments,0);
  const text = await storage.readText('c1');
  assert.equal(text.turns[0].question,'q1');
  db.close(); fs.rmSync(root,{recursive:true,force:true});
});
